namespace FinalApp
{
    partial class Stocks
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.labelEPSEstimateCurrentYear = new System.Windows.Forms.Label();
            this.labelPERatio = new System.Windows.Forms.Label();
            this.labelDividendShare = new System.Windows.Forms.Label();
            this.labelMarketCap = new System.Windows.Forms.Label();
            this.labelAsk = new System.Windows.Forms.Label();
            this.labelBid = new System.Windows.Forms.Label();
            this.labelAverageDailyVolume = new System.Windows.Forms.Label();
            this.labelVolume = new System.Windows.Forms.Label();
            this.labelweek52Range = new System.Windows.Forms.Label();
            this.labelDaysRange = new System.Windows.Forms.Label();
            this.labelOpen = new System.Windows.Forms.Label();
            this.labelPreviousClose = new System.Windows.Forms.Label();
            this.labelChangePercentChange = new System.Windows.Forms.Label();
            this.labelPrice = new System.Windows.Forms.Label();
            this.labelLastTradeTime = new System.Windows.Forms.Label();
            this.labelSymbol = new System.Windows.Forms.Label();
            this.label17 = new System.Windows.Forms.Label();
            this.label16 = new System.Windows.Forms.Label();
            this.label15 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.txtSymbol = new System.Windows.Forms.ComboBox();
            this.button9 = new System.Windows.Forms.Button();
            this.button8 = new System.Windows.Forms.Button();
            this.button7 = new System.Windows.Forms.Button();
            this.button6 = new System.Windows.Forms.Button();
            this.button5 = new System.Windows.Forms.Button();
            this.button4 = new System.Windows.Forms.Button();
            this.button3 = new System.Windows.Forms.Button();
            this.button2 = new System.Windows.Forms.Button();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // labelEPSEstimateCurrentYear
            // 
            this.labelEPSEstimateCurrentYear.AutoSize = true;
            this.labelEPSEstimateCurrentYear.BackColor = System.Drawing.SystemColors.Control;
            this.labelEPSEstimateCurrentYear.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.labelEPSEstimateCurrentYear.Location = new System.Drawing.Point(531, 180);
            this.labelEPSEstimateCurrentYear.Name = "labelEPSEstimateCurrentYear";
            this.labelEPSEstimateCurrentYear.Size = new System.Drawing.Size(10, 13);
            this.labelEPSEstimateCurrentYear.TabIndex = 87;
            this.labelEPSEstimateCurrentYear.Text = " ";
            // 
            // labelPERatio
            // 
            this.labelPERatio.AutoSize = true;
            this.labelPERatio.BackColor = System.Drawing.SystemColors.Control;
            this.labelPERatio.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.labelPERatio.Location = new System.Drawing.Point(531, 160);
            this.labelPERatio.Name = "labelPERatio";
            this.labelPERatio.Size = new System.Drawing.Size(10, 13);
            this.labelPERatio.TabIndex = 86;
            this.labelPERatio.Text = " ";
            // 
            // labelDividendShare
            // 
            this.labelDividendShare.AutoSize = true;
            this.labelDividendShare.BackColor = System.Drawing.SystemColors.Control;
            this.labelDividendShare.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.labelDividendShare.Location = new System.Drawing.Point(531, 140);
            this.labelDividendShare.Name = "labelDividendShare";
            this.labelDividendShare.Size = new System.Drawing.Size(10, 13);
            this.labelDividendShare.TabIndex = 85;
            this.labelDividendShare.Text = " ";
            // 
            // labelMarketCap
            // 
            this.labelMarketCap.AutoSize = true;
            this.labelMarketCap.BackColor = System.Drawing.SystemColors.Control;
            this.labelMarketCap.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.labelMarketCap.Location = new System.Drawing.Point(531, 120);
            this.labelMarketCap.Name = "labelMarketCap";
            this.labelMarketCap.Size = new System.Drawing.Size(10, 13);
            this.labelMarketCap.TabIndex = 84;
            this.labelMarketCap.Text = " ";
            // 
            // labelAsk
            // 
            this.labelAsk.AutoSize = true;
            this.labelAsk.BackColor = System.Drawing.SystemColors.Control;
            this.labelAsk.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.labelAsk.Location = new System.Drawing.Point(531, 100);
            this.labelAsk.Name = "labelAsk";
            this.labelAsk.Size = new System.Drawing.Size(10, 13);
            this.labelAsk.TabIndex = 83;
            this.labelAsk.Text = " ";
            // 
            // labelBid
            // 
            this.labelBid.AutoSize = true;
            this.labelBid.BackColor = System.Drawing.SystemColors.Control;
            this.labelBid.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.labelBid.Location = new System.Drawing.Point(531, 80);
            this.labelBid.Name = "labelBid";
            this.labelBid.Size = new System.Drawing.Size(10, 13);
            this.labelBid.TabIndex = 82;
            this.labelBid.Text = " ";
            // 
            // labelAverageDailyVolume
            // 
            this.labelAverageDailyVolume.AutoSize = true;
            this.labelAverageDailyVolume.BackColor = System.Drawing.SystemColors.Control;
            this.labelAverageDailyVolume.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.labelAverageDailyVolume.Location = new System.Drawing.Point(531, 60);
            this.labelAverageDailyVolume.Name = "labelAverageDailyVolume";
            this.labelAverageDailyVolume.Size = new System.Drawing.Size(10, 13);
            this.labelAverageDailyVolume.TabIndex = 81;
            this.labelAverageDailyVolume.Text = " ";
            // 
            // labelVolume
            // 
            this.labelVolume.AutoSize = true;
            this.labelVolume.BackColor = System.Drawing.SystemColors.Control;
            this.labelVolume.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.labelVolume.Location = new System.Drawing.Point(531, 40);
            this.labelVolume.Name = "labelVolume";
            this.labelVolume.Size = new System.Drawing.Size(10, 13);
            this.labelVolume.TabIndex = 80;
            this.labelVolume.Text = " ";
            // 
            // labelweek52Range
            // 
            this.labelweek52Range.AutoSize = true;
            this.labelweek52Range.BackColor = System.Drawing.SystemColors.Control;
            this.labelweek52Range.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.labelweek52Range.Location = new System.Drawing.Point(173, 180);
            this.labelweek52Range.Name = "labelweek52Range";
            this.labelweek52Range.Size = new System.Drawing.Size(10, 13);
            this.labelweek52Range.TabIndex = 79;
            this.labelweek52Range.Text = " ";
            // 
            // labelDaysRange
            // 
            this.labelDaysRange.AutoSize = true;
            this.labelDaysRange.BackColor = System.Drawing.SystemColors.Control;
            this.labelDaysRange.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.labelDaysRange.Location = new System.Drawing.Point(173, 160);
            this.labelDaysRange.Name = "labelDaysRange";
            this.labelDaysRange.Size = new System.Drawing.Size(10, 13);
            this.labelDaysRange.TabIndex = 78;
            this.labelDaysRange.Text = " ";
            // 
            // labelOpen
            // 
            this.labelOpen.AutoSize = true;
            this.labelOpen.BackColor = System.Drawing.SystemColors.Control;
            this.labelOpen.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.labelOpen.Location = new System.Drawing.Point(173, 140);
            this.labelOpen.Name = "labelOpen";
            this.labelOpen.Size = new System.Drawing.Size(10, 13);
            this.labelOpen.TabIndex = 77;
            this.labelOpen.Text = " ";
            // 
            // labelPreviousClose
            // 
            this.labelPreviousClose.AutoSize = true;
            this.labelPreviousClose.BackColor = System.Drawing.SystemColors.Control;
            this.labelPreviousClose.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.labelPreviousClose.Location = new System.Drawing.Point(173, 120);
            this.labelPreviousClose.Name = "labelPreviousClose";
            this.labelPreviousClose.Size = new System.Drawing.Size(10, 13);
            this.labelPreviousClose.TabIndex = 76;
            this.labelPreviousClose.Text = " ";
            // 
            // labelChangePercentChange
            // 
            this.labelChangePercentChange.AutoSize = true;
            this.labelChangePercentChange.BackColor = System.Drawing.SystemColors.Control;
            this.labelChangePercentChange.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.labelChangePercentChange.Location = new System.Drawing.Point(173, 100);
            this.labelChangePercentChange.Name = "labelChangePercentChange";
            this.labelChangePercentChange.Size = new System.Drawing.Size(10, 13);
            this.labelChangePercentChange.TabIndex = 75;
            this.labelChangePercentChange.Text = " ";
            // 
            // labelPrice
            // 
            this.labelPrice.AutoSize = true;
            this.labelPrice.BackColor = System.Drawing.SystemColors.Control;
            this.labelPrice.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.labelPrice.Location = new System.Drawing.Point(173, 80);
            this.labelPrice.Name = "labelPrice";
            this.labelPrice.Size = new System.Drawing.Size(10, 13);
            this.labelPrice.TabIndex = 74;
            this.labelPrice.Text = " ";
            // 
            // labelLastTradeTime
            // 
            this.labelLastTradeTime.AutoSize = true;
            this.labelLastTradeTime.BackColor = System.Drawing.SystemColors.Control;
            this.labelLastTradeTime.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.labelLastTradeTime.Location = new System.Drawing.Point(173, 60);
            this.labelLastTradeTime.Name = "labelLastTradeTime";
            this.labelLastTradeTime.Size = new System.Drawing.Size(10, 13);
            this.labelLastTradeTime.TabIndex = 73;
            this.labelLastTradeTime.Text = " ";
            // 
            // labelSymbol
            // 
            this.labelSymbol.AutoSize = true;
            this.labelSymbol.BackColor = System.Drawing.SystemColors.Control;
            this.labelSymbol.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.labelSymbol.Location = new System.Drawing.Point(173, 39);
            this.labelSymbol.Name = "labelSymbol";
            this.labelSymbol.Size = new System.Drawing.Size(10, 13);
            this.labelSymbol.TabIndex = 72;
            this.labelSymbol.Text = " ";
            // 
            // label17
            // 
            this.label17.AutoSize = true;
            this.label17.BackColor = System.Drawing.SystemColors.Control;
            this.label17.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label17.Location = new System.Drawing.Point(368, 180);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(133, 13);
            this.label17.TabIndex = 71;
            this.label17.Text = "EPS Estimate Current Year";
            // 
            // label16
            // 
            this.label16.AutoSize = true;
            this.label16.BackColor = System.Drawing.SystemColors.Control;
            this.label16.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label16.Location = new System.Drawing.Point(368, 160);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(54, 13);
            this.label16.TabIndex = 70;
            this.label16.Text = "P/E Ratio";
            // 
            // label15
            // 
            this.label15.AutoSize = true;
            this.label15.BackColor = System.Drawing.SystemColors.Control;
            this.label15.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label15.Location = new System.Drawing.Point(368, 140);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(82, 13);
            this.label15.TabIndex = 69;
            this.label15.Text = "Dividend/Share";
            // 
            // label14
            // 
            this.label14.AutoSize = true;
            this.label14.BackColor = System.Drawing.SystemColors.Control;
            this.label14.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label14.Location = new System.Drawing.Point(368, 120);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(62, 13);
            this.label14.TabIndex = 68;
            this.label14.Text = "Market Cap";
            // 
            // label13
            // 
            this.label13.AutoSize = true;
            this.label13.BackColor = System.Drawing.SystemColors.Control;
            this.label13.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label13.Location = new System.Drawing.Point(368, 100);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(25, 13);
            this.label13.TabIndex = 67;
            this.label13.Text = "Ask";
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.BackColor = System.Drawing.SystemColors.Control;
            this.label12.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label12.Location = new System.Drawing.Point(368, 80);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(22, 13);
            this.label12.TabIndex = 66;
            this.label12.Text = "Bid";
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.BackColor = System.Drawing.SystemColors.Control;
            this.label11.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label11.Location = new System.Drawing.Point(368, 60);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(111, 13);
            this.label11.TabIndex = 65;
            this.label11.Text = "Average Daily Volume";
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.BackColor = System.Drawing.SystemColors.Control;
            this.label10.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label10.Location = new System.Drawing.Point(368, 40);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(42, 13);
            this.label10.TabIndex = 64;
            this.label10.Text = "Volume";
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.BackColor = System.Drawing.SystemColors.Control;
            this.label9.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label9.Location = new System.Drawing.Point(11, 180);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(83, 13);
            this.label9.TabIndex = 63;
            this.label9.Text = "52-week Range";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.BackColor = System.Drawing.SystemColors.Control;
            this.label8.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label8.Location = new System.Drawing.Point(11, 160);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(72, 13);
            this.label8.TabIndex = 62;
            this.label8.Text = "Day’s Range ";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.BackColor = System.Drawing.SystemColors.Control;
            this.label7.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label7.Location = new System.Drawing.Point(11, 140);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(33, 13);
            this.label7.TabIndex = 61;
            this.label7.Text = "Open";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.SystemColors.Control;
            this.label6.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label6.Location = new System.Drawing.Point(11, 120);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(77, 13);
            this.label6.TabIndex = 60;
            this.label6.Text = "Previous Close";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.SystemColors.Control;
            this.label5.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label5.Location = new System.Drawing.Point(11, 100);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(145, 13);
            this.label5.TabIndex = 59;
            this.label5.Text = "Change and Percent Change";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.SystemColors.Control;
            this.label4.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label4.Location = new System.Drawing.Point(11, 80);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(31, 13);
            this.label4.TabIndex = 58;
            this.label4.Text = "Price";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.SystemColors.Control;
            this.label3.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label3.Location = new System.Drawing.Point(11, 60);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(84, 13);
            this.label3.TabIndex = 57;
            this.label3.Text = "Last Trade Time";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.SystemColors.Control;
            this.label2.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label2.Location = new System.Drawing.Point(11, 40);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(84, 13);
            this.label2.TabIndex = 56;
            this.label2.Text = "Last Trade Date";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.SystemColors.Control;
            this.label1.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label1.Location = new System.Drawing.Point(137, 15);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(311, 13);
            this.label1.TabIndex = 55;
            this.label1.Text = "iShares MSCI All Country Asia Information Technology Index Fun";
            // 
            // txtSymbol
            // 
            this.txtSymbol.BackColor = System.Drawing.SystemColors.Control;
            this.txtSymbol.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.txtSymbol.FormattingEnabled = true;
            this.txtSymbol.Items.AddRange(new object[] {
            "AAIT",
            "AAL",
            "AALCP",
            "AAME",
            "AAOI",
            "AAON",
            "AAPL",
            "AAWW",
            "AAXJ",
            "ABAX",
            "ABCB",
            "ABCD",
            "ABCO",
            "ABFS",
            "ABGB",
            "ABIO",
            "ABMD",
            "ABTL",
            "ACAD",
            "ACAS",
            "ACAT",
            "ACCL",
            "ACET",
            "ACFC",
            "ACFN",
            "ACGL",
            "ACHC",
            "ACHN",
            "ACIW",
            "ACLS",
            "ACNB",
            "ACOR",
            "ACPW",
            "ACRX",
            "ACSF",
            "ACST",
            "ACTG",
            "ACTS",
            "ACUR",
            "ACWI",
            "ACWX",
            "ACXM",
            "ADAT",
            "ADBE",
            "ADEP",
            "ADES",
            "ADHD",
            "ADI",
            "ADMP",
            "ADNC",
            "ADP",
            "ADRA",
            "ADRD",
            "ADRE",
            "ADRU",
            "ADSK",
            "ADTN",
            "ADUS",
            "ADVS",
            "ADXS",
            "ADXSW",
            "AEGN",
            "AEGR",
            "AEHR",
            "AEIS",
            "AEPI",
            "AERI",
            "AETI",
            "AEY",
            "AEZS",
            "AFAM",
            "AFCB",
            "AFFX",
            "AFH",
            "AFOP",
            "AFSI",
            "AGEN",
            "AGII",
            "AGIIL",
            "AGIO",
            "AGNC",
            "AGNCP",
            "AGND",
            "AGYS",
            "AGZD",
            "AHGP",
            "AHPI",
            "AIMC",
            "AINV",
            "AIQ",
            "AIRM",
            "AIRR",
            "AIRT",
            "AIXG",
            "AKAM",
            "AKAO",
            "AKER",
            "AKRX",
            "ALCO",
            "ALCS",
            "ALGN",
            "ALGT",
            "ALIM",
            "ALKS",
            "ALLB",
            "ALLT",
            "ALNY",
            "ALOG",
            "ALOT",
            "ALQA",
            "ALSK",
            "ALTI",
            "ALTR",
            "ALXA",
            "ALXN",
            "AMAG",
            "AMAP",
            "AMAT",
            "AMBA",
            "AMBC",
            "AMBCW",
            "AMBI",
            "AMBT",
            "AMCC",
            "AMCF",
            "AMCN",
            "AMCX",
            "AMDA",
            "AMED",
            "AMGN",
            "AMIC",
            "AMKR",
            "AMNB",
            "AMOT",
            "AMOV",
            "AMRB",
            "AMRI",
            "AMRN",
            "AMRS",
            "AMSC",
            "AMSF",
            "AMSG",
            "AMSWA",
            "AMWD",
            "AMZN",
            "ANAC",
            "ANAD",
            "ANAT",
            "ANCB",
            "ANCI",
            "ANCX",
            "ANDE",
            "ANGI",
            "ANGO",
            "ANIK",
            "ANIP",
            "ANSS",
            "ANTH",
            "AOSL",
            "APAGF",
            "APEI",
            "APOG",
            "APOL",
            "APPY",
            "APRI",
            "APSA",
            "APWC",
            "AQU",
            "AQUUU",
            "AQUUW",
            "AQXP",
            "ARAY",
            "ARCC",
            "ARCI",
            "ARCP",
            "ARCPP",
            "ARCW",
            "AREX",
            "ARGS",
            "ARIA",
            "ARII",
            "ARIS",
            "ARKR",
            "ARLP",
            "ARMH",
            "ARNA",
            "AROW",
            "ARQL",
            "ARRS",
            "ARRY",
            "ARTC",
            "ARTNA",
            "ARTW",
            "ARTX",
            "ARUN",
            "ARWR",
            "ASBB",
            "ASBC",
            "ASBCW",
            "ASBI",
            "ASCMA",
            "ASDR",
            "ASEI",
            "ASFI",
            "ASMI",
            "ASML",
            "ASNA",
            "ASPS",
            "ASPX",
            "ASRV",
            "ASRVP",
            "ASTC",
            "ASTE",
            "ASTI",
            "ASTM",
            "ASUR",
            "ASYS",
            "ATAI",
            "ATAX",
            "ATEA",
            "ATEC",
            "ATHN",
            "ATHX",
            "ATLC",
            "ATLO",
            "ATMI",
            "ATML",
            "ATNI",
            "ATNY",
            "ATOS",
            "ATRC",
            "ATRI",
            "ATRM",
            "ATRO",
            "ATRS",
            "ATSG",
            "ATTU",
            "ATVI",
            "AUBN",
            "AUDC",
            "AUXL",
            "AVAV",
            "AVEO",
            "AVGO",
            "AVHI",
            "AVNR",
            "AVNW",
            "AWAY",
            "AWRE",
            "AXAS",
            "AXDX",
            "AXFN",
            "AXGN",
            "AXJS",
            "AXTI",
            "AZPN",
            "BABY",
            "BAGL",
            "BAGR",
            "BAMM",
            "BANC",
            "BANCL",
            "BANCP",
            "BANF",
            "BANFP",
            "BANR",
            "BANX",
            "BASI",
            "BAXS",
            "BBBY",
            "BBCN",
            "BBEP",
            "BBGI",
            "BBNK",
            "BBOX",
            "BBRG",
            "BBRY",
            "BBSI",
            "BCBP",
            "BCOM",
            "BCOR",
            "BCOV",
            "BCPC",
            "BCRX",
            "BDBD",
            "BDE",
            "BDGE",
            "BDMS",
            "BDSI",
            "BEAT",
            "BEAV",
            "BEBE",
            "BECN",
            "BELFA",
            "BELFB",
            "BFIN",
            "BGCP",
            "BGFV",
            "BGMD",
            "BIB",
            "BICK",
            "BIDU",
            "BIIB",
            "BIND",
            "BIOC",
            "BIOD",
            "BIOF",
            "BIOL",
            "BIOS",
            "BIRT",
            "BIS",
            "BJRI",
            "BKCC",
            "BKEP",
            "BKEPP",
            "BKMU",
            "BKSC",
            "BKYF",
            "BLDP",
            "BLDR",
            "BLIN          ",
            "BLKB",
            "BLMN",
            "BLMT",
            "BLRX",
            "BLUE",
            "BLVDU",
            "BMRC",
            "BMRN",
            "BMTC",
            "BNCL",
            "BNCN",
            "BNDX",
            "BNFT",
            "BNSO",
            "BOBE",
            "BOCH",
            "BODY",
            "BOFI",
            "BOKF",
            "BOLT",
            "BONA",
            "BONT",
            "BOOM",
            "BOSC",
            "BOTA",
            "BOTJ",
            "BPFH",
            "BPFHP",
            "BPFHW",
            "BPHX",
            "BPOP",
            "BPOPM",
            "BPOPN",
            "BPTH",
            "BRCD",
            "BRCM",
            "BREW",
            "BRID",
            "BRKL",
            "BRKR",
            "BRKS",
            "BRLI",
            "BSDM",
            "BSET",
            "BSFT",
            "BSPM",
            "BSQR",
            "BSRR",
            "BSTC",
            "BTUI",
            "BUR",
            "BUSE",
            "BV",
            "BVA",
            "BVSN",
            "BWEN",
            "BWINA",
            "BWINB",
            "BWLD",
            "BYBK",
            "BYFC",
            "BYLK",
            "CA",
            "CAAS",
            "CAC",
            "CACB",
            "CACC",
            "CACG",
            "CACGU",
            "CACGW",
            "CACH",
            "CACQ",
            "CADC",
            "CADX",
            "CAKE",
            "CALD",
            "CALI",
            "CALL",
            "CALM",
            "CAMB",
            "CAMBU",
            "CAMBW",
            "CAMP",
            "CAMT",
            "CAR",
            "CARA",
            "CARB",
            "CART",
            "CARV",
            "CARZ",
            "CASH",
            "CASM",
            "CASS",
            "CASY",
            "CATM",
            "CATY",
            "CATYW",
            "CAVM",
            "CBAK",
            "CBAN",
            "CBEY",
            "CBF",
            "CBIN",
            "CBLI",
            "CBMX",
            "CBMXW",
            "CBNJ",
            "CBNK",
            "CBOE",
            "CBPO",
            "CBRL",
            "CBRX",
            "CBSH",
            "CBST",
            "CBSTZ",
            "CCBG",
            "CCCL",
            "CCCR",
            "CCIH",
            "CCMP",
            "CCNE",
            "CCOI",
            "CCRN",
            "CCUR",
            "CCXI",
            "CDNS",
            "CDTI",
            "CDW",
            "CDXS",
            "CDZI",
            "CECE",
            "CECO",
            "CEDU",
            "CELG",
            "CELGZ",
            "CEMI",
            "CEMP",
            "CENT",
            "CENTA",
            "CENX",
            "CERE",
            "CERN",
            "CERS",
            "CETV",
            "CEVA",
            "CFBK",
            "CFFI",
            "CFFN",
            "CFNB",
            "CFNL",
            "CG",
            "CGEN",
            "CGIX",
            "CGNX",
            "CGO",
            "CHCI",
            "CHCO",
            "CHDN",
            "CHDX",
            "CHEF",
            "CHEV",
            "CHFC",
            "CHFN",
            "CHI",
            "CHKE",
            "CHKP",
            "CHLN",
            "CHMG",
            "CHNR",
            "CHOP",
            "CHRM",
            "CHRW",
            "CHSCN",
            "CHSCO",
            "CHSCP",
            "CHTP",
            "CHTR",
            "CHUY",
            "CHW",
            "CHXF",
            "CHY",
            "CHYR",
            "CIDM",
            "CIFC",
            "CIMT",
            "CINF",
            "CISAA",
            "CISAU",
            "CISAW",
            "CISG",
            "CIZN",
            "CJJD",
            "CKEC",
            "CKSW",
            "CLAC",
            "CLACU",
            "CLACW",
            "CLBH",
            "CLCT",
            "CLDN",
            "CLDX",
            "CLFD",
            "CLIR",
            "CLMS",
            "CLMT",
            "CLNE",
            "CLNT",
            "CLRO",
            "CLRX",
            "CLSN",
            "CLTX",
            "CLUB",
            "CLVS",
            "CLWT",
            "CMCO",
            "CMCSA",
            "CMCSK",
            "CME",
            "CMFN",
            "CMGE",
            "CMLS",
            "CMRX",
            "CMSB",
            "CMTL",
            "CNAT",
            "CNBC",
            "CNBKA",
            "CNCE",
            "CNDO",
            "CNET",
            "CNIT",
            "CNMD",
            "CNOB",
            "CNQR",
            "CNSI",
            "CNSL",
            "CNTF",
            "CNTY",
            "CNVR",
            "CNYD",
            "COA           ",
            "COB",
            "COBK",
            "COBR",
            "COBZ",
            "COCO",
            "COHR",
            "COHU",
            "COKE",
            "COLB",
            "COLM",
            "COMM",
            "CONE",
            "CONN",
            "COOL",
            "CORE",
            "CORT",
            "COSI",
            "COST",
            "COVS",
            "COWN",
            "CPAH",
            "CPGI",
            "CPHC",
            "CPHD",
            "CPIX",
            "CPLA",
            "CPLP",
            "CPRT",
            "CPRX",
            "CPSI",
            "CPSL",
            "CPSS",
            "CPST",
            "CPTA",
            "CPWR",
            "CPXX",
            "CRAI",
            "CRAY",
            "CRDC",
            "CRDS",
            "CREE",
            "CREG",
            "CRESW",
            "CRESY",
            "CRIS",
            "CRMB",
            "CRMBU",
            "CRMBW",
            "CRME",
            "CRMT",
            "CRNT",
            "CROX",
            "CRRC",
            "CRRS",
            "CRTO",
            "CRUS",
            "CRVL",
            "CRWN",
            "CRWS",
            "CRZO",
            "CSBK",
            "CSCD",
            "CSCO",
            "CSFL",
            "CSGP",
            "CSGS",
            "CSII",
            "CSIQ",
            "CSOD",
            "CSPI",
            "CSQ",
            "CSRE",
            "CSTE",
            "CSUN",
            "CSWC",
            "CTAS",
            "CTBI",
            "CTCM",
            "CTCT",
            "CTG",
            "CTHR",
            "CTIB",
            "CTIC",
            "CTRL",
            "CTRN",
            "CTRP",
            "CTRX",
            "CTSH",
            "CTWS",
            "CTXS",
            "CU",
            "CUBA",
            "CUBI",
            "CUBIL",
            "CUI",
            "CUNB",
            "CUTR",
            "CVBF",
            "CVCO",
            "CVCY",
            "CVGI",
            "CVGW",
            "CVLT",
            "CVLY",
            "CVTI",
            "CVV",
            "CWAY",
            "CWBC",
            "CWCO",
            "CWST",
            "CWTR",
            "CXDC",
            "CY",
            "CYAN",
            "CYBE",
            "CYBX",
            "CYCC",
            "CYCCP",
            "CYHHZ",
            "CYNO",
            "CYOU",
            "CYRN",
            "CYTK",
            "CYTR",
            "CYTX",
            "CYTXW",
            "CZFC",
            "CZNC",
            "CZR",
            "CZWI",
            "DAEG",
            "DAIO",
            "DAKT",
            "DARA",
            "DATE",
            "DAVE",
            "DBLE",
            "DBLEP",
            "DCIN",
            "DCIX",
            "DCOM",
            "DCTH",
            "DECK",
            "DENN",
            "DEPO",
            "DEST",
            "DFRG",
            "DFZ",
            "DGAS",
            "DGICA",
            "DGICB",
            "DGII",
            "DGLD",
            "DGLY",
            "DGRE",
            "DGRS",
            "DGRW",
            "DHIL",
            "DHRM",
            "DIOD",
            "DISCA",
            "DISCB",
            "DISCK",
            "DISH",
            "DJCO",
            "DLHC",
            "DLIA",
            "DLLR",
            "DLNG",
            "DLTR",
            "DMLP",
            "DMND",
            "DMRC",
            "DNBF",
            "DNDN",
            "DNKN",
            "DORM",
            "DOVR",
            "DOX",
            "DPRX",
            "DRAD",
            "DRAM",
            "DRIV",
            "DRNA",
            "DRRX",
            "DRTX",
            "DRWI",
            "DRYS",
            "DSCI",
            "DSCO",
            "DSGX",
            "DSKX",
            "DSLV",
            "DSPG",
            "DSWL",
            "DTLK",
            "DTSI",
            "DTV",
            "DVAX",
            "DVCR",
            "DWA",
            "DWCH",
            "DWSN",
            "DXCM",
            "DXGE",
            "DXJS",
            "DXKW",
            "DXLG",
            "DXM",
            "DXPE",
            "DXPS",
            "DXYN",
            "DYAX",
            "DYNT",
            "DYSL",
            "EA",
            "EAC           ",
            "EAGL",
            "EAGLU",
            "EAGLW",
            "EBAY",
            "EBIO",
            "EBIX",
            "EBMT",
            "EBSB",
            "EBTC",
            "ECHO",
            "ECOL",
            "ECPG",
            "ECTE",
            "ECYT",
            "EDAP",
            "EDGW",
            "EDMC",
            "EDS",
            "EDUC",
            "EEFT",
            "EEI",
            "EEMA",
            "EEME",
            "EEML",
            "EFII",
            "EFSC",
            "EFUT",
            "EGAN",
            "EGBN",
            "EGHT",
            "EGLE",
            "EGLT",
            "EGOV",
            "EGRW",
            "EGRX",
            "EGT",
            "EHTH",
            "EIGI",
            "ELGX",
            "ELNK",
            "ELON",
            "ELOS",
            "ELRC",
            "ELSE",
            "ELTK",
            "EMCB",
            "EMCF",
            "EMCG",
            "EMCI",
            "EMDI",
            "EMDR",
            "EMEY",
            "EMFN",
            "EMIF",
            "EMITF",
            "EMKR",
            "EML",
            "EMMS",
            "EMMSP",
            "EMMT",
            "ENDP",
            "ENG",
            "ENMD",
            "ENOC",
            "ENPH",
            "ENSG",
            "ENT",
            "ENTA",
            "ENTG",
            "ENTR",
            "ENVI",
            "ENZN",
            "ENZY          ",
            "EONC",
            "EOPN",
            "EPAX",
            "EPAY",
            "EPIQ",
            "EPZM",
            "EQIX",
            "ERIC",
            "ERIE",
            "ERII",
            "EROC",
            "ERS",
            "ERW",
            "ESBF",
            "ESBK",
            "ESCA",
            "ESEA",
            "ESGR",
            "ESIO",
            "ESLT",
            "ESMC",
            "ESPR",
            "ESRX",
            "ESSA",
            "ESSX",
            "ESXB",
            "ESYS",
            "ETFC",
            "ETRM",
            "EUFN",
            "EVAL",
            "EVBS",
            "EVEP",
            "EVOK",
            "EVOL",
            "EVRY",
            "EWBC",
            "EXA",
            "EXAC",
            "EXAS",
            "EXEL",
            "EXFO",
            "EXLP",
            "EXLS",
            "EXPD",
            "EXPE",
            "EXPO",
            "EXTR",
            "EXXI",
            "EZCH",
            "EZPW",
            "FALC",
            "FANG",
            "FARM",
            "FARO",
            "FAST",
            "FATE",
            "FB",
            "FBIZ",
            "FBMI",
            "FBMS",
            "FBNC",
            "FBNK",
            "FBRC",
            "FBSS",
            "FCAP",
            "FCBC",
            "FCCO",
            "FCCY",
            "FCEL",
            "FCFS",
            "FCHI",
            "FCLF",
            "FCNCA",
            "FCS",
            "FCTY",
            "FCVA",
            "FCZA",
            "FCZAP",
            "FDEF",
            "FDML",
            "FDUS",
            "FEFN",
            "FEIC",
            "FEIM",
            "FELE",
            "FES",
            "FEYE",
            "FFBC",
            "FFBCW",
            "FFBH",
            "FFCO",
            "FFHL",
            "FFIC",
            "FFIN",
            "FFIV",
            "FFKT",
            "FFKY",
            "FFNM",
            "FFNW",
            "FHCO",
            "FIBK",
            "FINL",
            "FISH",
            "FISI",
            "FISV",
            "FITB",
            "FITBI",
            "FIVE",
            "FIZZ",
            "FLDM",
            "FLEX",
            "FLIC",
            "FLIR",
            "FLL",
            "FLML",
            "FLWS",
            "FLXN",
            "FLXS",
            "FMBI",
            "FMER",
            "FMI",
            "FMNB",
            "FNFG",
            "FNGN",
            "FNHC",
            "FNLC",
            "FNRG",
            "FNSR",
            "FOLD",
            "FONE",
            "FONR",
            "FORD",
            "FORM",
            "FORR",
            "FORTY",
            "FOSL",
            "FOX",
            "FOXA",
            "FOXF",
            "FPRX",
            "FRAN",
            "FRBA",
            "FRBK",
            "FRED",
            "FREE",
            "FRGI",
            "FRME",
            "FRNK",
            "FRP",
            "FSBK",
            "FSBW",
            "FSC",
            "FSCFL",
            "FSFG",
            "FSFR",
            "FSGI",
            "FSLR",
            "FSRV",
            "FSTR",
            "FSYS",
            "FTCS",
            "FTD",
            "FTEK",
            "FTGC",
            "FTHI",
            "FTLB",
            "FTNT",
            "FTR",
            "FTSL",
            "FUBC",
            "FUEL",
            "FULL",
            "FULLL",
            "FULT",
            "FUNC",
            "FUND",
            "FURX",
            "FV",
            "FWLT",
            "FWM",
            "FWRD",
            "FXCB",
            "FXEN",
            "GABC",
            "GAGA",
            "GAI",
            "GAIA",
            "GAIN",
            "GAINP",
            "GALE",
            "GALT",
            "GALTU",
            "GALTW",
            "GAME",
            "GARS",
            "GASS",
            "GBCI",
            "GBDC",
            "GBLI",
            "GBNK",
            "GCBC",
            "GCVRZ",
            "GDEF",
            "GENC",
            "GENE",
            "GEOS",
            "GERN",
            "GEVA",
            "GEVO",
            "GFED",
            "GFN",
            "GFNCP",
            "GGAL",
            "GHDX",
            "GIFI",
            "GIGA",
            "GIGM",
            "GIII",
            "GILD",
            "GILT",
            "GK",
            "GKNT",
            "GLAD",
            "GLADP",
            "GLBS",
            "GLBZ",
            "GLCB",
            "GLCH",
            "GLDC",
            "GLDD",
            "GLDI",
            "GLMD",
            "GLNG",
            "GLPI",
            "GLPW",
            "GLRE",
            "GLUU",
            "GLYC",
            "GMAN",
            "GMCR",
            "GMETP",
            "GMLP",
            "GNCA",
            "GNCMA",
            "GNMA",
            "GNMK",
            "GNTX",
            "GNVC",
            "GOGO",
            "GOLD",
            "GOMO",
            "GOOD",
            "GOODN",
            "GOODO",
            "GOODP",
            "GOOG",
            "GPIC",
            "GPOR",
            "GPRC",
            "GPRE",
            "GRFS",
            "GRID",
            "GRIF",
            "GRMN",
            "GROW",
            "GRPN",
            "GRVY",
            "GSBC",
            "GSIG",
            "GSIT",
            "GSJK",
            "GSM",
            "GSOL",
            "GSVC",
            "GT",
            "GTAT",
            "GTIM",
            "GTIV",
            "GTLS",
            "GTPPP",
            "GTWN",
            "GTXI",
            "GUID",
            "GULF",
            "GURE",
            "GWPH",
            "GYRO",
            "HA",
            "HAFC",
            "HAIN",
            "HALL",
            "HALO",
            "HART          ",
            "HAS",
            "HAST",
            "HAWK",
            "HAYN",
            "HBAN",
            "HBANP",
            "HBCP",
            "HBHC",
            "HBIO",
            "HBK",
            "HBMD",
            "HBNC",
            "HBNK",
            "HBOS",
            "HBP",
            "HCAC",
            "HCACU",
            "HCACW",
            "HCAP",
            "HCBK",
            "HCCI",
            "HCKT",
            "HCOM",
            "HCSG",
            "HDNG",
            "HDS",
            "HDSN",
            "HEES",
            "HELE",
            "HEOP",
            "HERO",
            "HFBC",
            "HFBL",
            "HFFC",
            "HFWA",
            "HGSH",
            "HIBB",
            "HIFS",
            "HIHO",
            "HIIQ",
            "HILL",
            "HIMX",
            "HITK",
            "HITT",
            "HKTV",
            "HLIT",
            "HLSS",
            "HMHC",
            "HMIN",
            "HMNF",
            "HMNY",
            "HMPR",
            "HMST",
            "HMSY",
            "HMTV",
            "HNH",
            "HNRG",
            "HNSN",
            "HOFT",
            "HOLI",
            "HOLX",
            "HOMB",
            "HOME",
            "HOTR",
            "HOTRW",
            "HOVNP",
            "HPAC",
            "HPJ",
            "HPTX",
            "HRTX",
            "HRZN",
            "HSIC",
            "HSII",
            "HSKA",
            "HSNI",
            "HSOL",
            "HSON",
            "HSTM",
            "HTBI",
            "HTBK",
            "HTBX",
            "HTCH",
            "HTCO",
            "HTHT",
            "HTLD",
            "HTLF",
            "HTWO",
            "HTWR",
            "HUBG",
            "HURC",
            "HURN",
            "HWAY",
            "HWBK",
            "HWCC",
            "HWKN",
            "HYGS",
            "HYLS",
            "HYND",
            "HYZD",
            "HZNP",
            "IACI",
            "IART",
            "IBB",
            "IBCA",
            "IBCP",
            "IBKC",
            "IBKR",
            "IBOC",
            "IBTX",
            "ICAD",
            "ICCC",
            "ICEL",
            "ICFI",
            "ICGE",
            "ICLD",
            "ICLDW",
            "ICLN",
            "ICLR",
            "ICON",
            "ICPT",
            "ICUI",
            "IDCC",
            "IDIX",
            "IDRA",
            "IDSA",
            "IDSY",
            "IDTI",
            "IDXX",
            "IEP",
            "IESC",
            "IFAS",
            "IFEU",
            "IFGL",
            "IFNA",
            "IFON",
            "IFSM",
            "IGLD",
            "IGOV",
            "IGTE",
            "III",
            "IIIN",
            "IIJI",
            "IILG",
            "IIN",
            "IIVI",
            "IKAN",
            "IKGH",
            "IKNX",
            "ILMN",
            "IMCB",
            "IMGN",
            "IMI",
            "IMKTA",
            "IMMR",
            "IMMU",
            "IMMY",
            "IMOS",
            "IMRS",
            "INAP",
            "INBK",
            "INCY",
            "INDB",
            "INDY",
            "INFA",
            "INFI",
            "INFN",
            "INGN",
            "ININ",
            "INOD",
            "INPH",
            "INSM",
            "INSY",
            "INTC",
            "INTG",
            "INTL",
            "INTLL",
            "INTU",
            "INTX",
            "INVE",
            "INWK",
            "INXB",
            "INXBU",
            "INXBW",
            "IOSP",
            "IPAR",
            "IPAS",
            "IPCC",
            "IPCI",
            "IPCM",
            "IPDN",
            "IPGP",
            "IPHS",
            "IPKW",
            "IPWR",
            "IPXL",
            "IQNT",
            "IRBT",
            "IRDM",
            "IRDMZ",
            "IRG",
            "IRIX",
            "IROQ",
            "IRWD",
            "ISBC",
            "ISCA",
            "ISHG",
            "ISIG",
            "ISIL",
            "ISIS",
            "ISLE",
            "ISM",
            "ISNS",
            "ISRG",
            "ISRL",
            "ISSC",
            "ISSI",
            "ITCI",
            "ITIC",
            "ITMN",
            "ITRI",
            "ITRN",
            "IVAC",
            "IVAN",
            "IXYS",
            "JACK",
            "JACQ",
            "JACQU",
            "JACQW",
            "JAKK",
            "JASO",
            "JAXB",
            "JAZZ",
            "JBHT",
            "JBLU",
            "JBSS",
            "JCOM",
            "JCS",
            "JCTCF",
            "JDSU",
            "JFBI",
            "JGBB",
            "JIVE",
            "JJSF",
            "JKHY",
            "JMBA",
            "JOBS",
            "JOEZ",
            "JOSB",
            "JOUT",
            "JRCC",
            "JRJC",
            "JSM",
            "JST",
            "JTPY",
            "JVA",
            "JXSB",
            "KALU",
            "KBALB",
            "KBIO",
            "KCAP",
            "KCLI",
            "KELYA",
            "KELYB",
            "KEQU",
            "KERX",
            "KEYW",
            "KFFB",
            "KFRC",
            "KFX",
            "KGJI",
            "KIN",
            "KINS",
            "KIOR",
            "KIPO",
            "KIPS",
            "KIRK",
            "KLAC",
            "KLIC",
            "KMDA",
            "KNDI",
            "KONA",
            "KONE",
            "KONG",
            "KOOL",
            "KOPN",
            "KOSS",
            "KPTI",
            "KRFT",
            "KRNY",
            "KTCC",
            "KTEC",
            "KTOS",
            "KUTV",
            "KVHI",
            "KWEB",
            "KYTH",
            "LABC",
            "LABL",
            "LACO",
            "LAKE",
            "LAMR",
            "LANC",
            "LAND",
            "LARK",
            "LAWS",
            "LAYN",
            "LBAI",
            "LBIX",
            "LBTYA",
            "LBTYB",
            "LBTYK",
            "LCAV",
            "LCNB",
            "LCUT",
            "LDRH",
            "LEAP",
            "LECO",
            "LEDS",
            "LEVY",
            "LEVYU",
            "LEVYW",
            "LFUS",
            "LFVN",
            "LGCY",
            "LGIH",
            "LGND",
            "LHCG",
            "LIME",
            "LINC",
            "LINE",
            "LINTA",
            "LINTB",
            "LION",
            "LIOX",
            "LIQD",
            "LIVE",
            "LIWA",
            "LJPC",
            "LKFN",
            "LKQ",
            "LLEN",
            "LLEX",
            "LLNW",
            "LLTC",
            "LMAT",
            "LMCA",
            "LMCB",
            "LMIA",
            "LMNR",
            "LMNS",
            "LMNX",
            "LMOS",
            "LNBB",
            "LNCE",
            "LNCO",
            "LNDC",
            "LOAN",
            "LOCM",
            "LOGI",
            "LOGM",
            "LOJN",
            "LONG",
            "LOOK",
            "LOPE",
            "LORL",
            "LPDX",
            "LPHI",
            "LPLA",
            "LPNT",
            "LPSB",
            "LPSN",
            "LPTH",
            "LPTN",
            "LQDT",
            "LRAD",
            "LRCX",
            "LSBI",
            "LSBK",
            "LSCC",
            "LSI",
            "LSTR",
            "LTBR",
            "LTRE",
            "LTRX",
            "LTXC",
            "LULU",
            "LUNA",
            "LVNTA",
            "LVNTB",
            "LWAY",
            "LXRX",
            "LYTS",
            "MACK",
            "MAG",
            "MAGS",
            "MAMS",
            "MANH",
            "MANT",
            "MAR",
            "MARK",
            "MARPS",
            "MASC",
            "MASI",
            "MAT",
            "MATR",
            "MATW",
            "MAYS",
            "MBFI",
            "MBII",
            "MBIS",
            "MBLX",
            "MBRG",
            "MBTF",
            "MBUU",
            "MBVT",
            "MBWM",
            "MCBC",
            "MCBK",
            "MCEP",
            "MCGC",
            "MCHP",
            "MCHX",
            "MCOX",
            "MCRI",
            "MCRL",
            "MCRS",
            "MDAS",
            "MDCA",
            "MDCI",
            "MDCO",
            "MDIV",
            "MDLZ",
            "MDRX",
            "MDSO",
            "MDVN",
            "MDXG",
            "MEAS",
            "MEIL",
            "MEILW",
            "MEILZ",
            "MEIP",
            "MELA",
            "MELI",
            "MEMP",
            "MENT",
            "MEOH",
            "MERC",
            "MERU",
            "METR",
            "MFI",
            "MFLX",
            "MFNC",
            "MFRI",
            "MFRM",
            "MFSF",
            "MGAM",
            "MGCD",
            "MGEE",
            "MGI",
            "MGIC",
            "MGLN",
            "MGNX",
            "MGPI",
            "MGRC",
            "MGYR",
            "MHGC",
            "MHLD",
            "MHLDO",
            "MICT",
            "MICTW",
            "MIDD",
            "MIND",
            "MINI",
            "MITK",
            "MITL",
            "MKSI",
            "MKTO",
            "MKTX",
            "MLAB",
            "MLHR",
            "MLNK",
            "MLNX",
            "MLVF",
            "MMLP",
            "MMSI",
            "MMYT",
            "MNDL",
            "MNDO",
            "MNGA",
            "MNKD",
            "MNOV",
            "MNRK",
            "MNRO",
            "MNST",
            "MNTA",
            "MNTG",
            "MNTX",
            "MOBI",
            "MOCO",
            "MOFG",
            "MONT",
            "MORN",
            "MOSY",
            "MOVE",
            "MPAA",
            "MPB",
            "MPEL",
            "MPET",
            "MPWR",
            "MRCC",
            "MRCY",
            "MRGE",
            "MRLN",
            "MRTN",
            "MRTX",
            "MRVL",
            "MSBF",
            "MSCC",
            "MSEX",
            "MSFG",
            "MSFT",
            "MSG",
            "MSLI",
            "MSON",
            "MSTR",
            "MTEX",
            "MTGE",
            "MTRX",
            "MTSC",
            "MTSI",
            "MTSL",
            "MTSN",
            "MU",
            "MVIS",
            "MWIV",
            "MWRX",
            "MXIM",
            "MXWL",
            "MYGN",
            "MYL",
            "MYRG",
            "MZOR",
            "NAII",
            "NANO",
            "NASB",
            "NATH",
            "NATI",
            "NATL",
            "NATR",
            "NAUH",
            "NAVG",
            "NBBC",
            "NBCB",
            "NBIX",
            "NBN",
            "NBS",
            "NBTB",
            "NBTF",
            "NCBC",
            "NCIT",
            "NCLH",
            "NCMI",
            "NCTY",
            "NDAQ",
            "NDLS",
            "NDSN",
            "NECB",
            "NEO",
            "NEOG",
            "NEON",
            "NEPT",
            "NETE",
            "NEWL",
            "NEWP",
            "NEWS",
            "NEWT",
            "NFBK",
            "NFEC",
            "NFLX",
            "NGHC",
            "NGPC",
            "NHTB",
            "NICE",
            "NICK",
            "NIHD",
            "NILE",
            "NINE",
            "NKSH",
            "NKTR",
            "NLNK",
            "NLST",
            "NMIH",
            "NMRX",
            "NNBR",
            "NOVB",
            "NPBC",
            "NPSP",
            "NRCIA",
            "NRCIB",
            "NRIM",
            "NRX",
            "NSEC",
            "NSIT",
            "NSPH",
            "NSSC",
            "NSTG",
            "NSYS",
            "NTAP",
            "NTCT",
            "NTES",
            "NTGR",
            "NTIC",
            "NTK",
            "NTLS",
            "NTRI",
            "NTRS",
            "NTWK",
            "NUAN",
            "NUCL",
            "NURO",
            "NUTR",
            "NUVA",
            "NVAX",
            "NVDA",
            "NVDQ",
            "NVEC",
            "NVEE",
            "NVEEW",
            "NVFY",
            "NVGN",
            "NVMI",
            "NVSL",
            "NVTL",
            "NWBI",
            "NWBO",
            "NWBOW",
            "NWFL",
            "NWLI",
            "NWPX",
            "NWS",
            "NWSA",
            "NXPI",
            "NXST",
            "NXTM",
            "NYMT",
            "NYMTP",
            "NYMX",
            "NYNY",
            "OABC",
            "OBAF",
            "OBAS",
            "OBCI",
            "OCC",
            "OCFC",
            "OCLR",
            "OCLS",
            "OCRX",
            "ODFL",
            "OFED",
            "OFIX",
            "OFLX",
            "OFS",
            "OGXI",
            "OHRP",
            "OIIM",
            "OINK",
            "OKSB",
            "OLBK",
            "OLED",
            "OMAB",
            "OMCL",
            "OMED",
            "OMER",
            "OMEX",
            "ONB",
            "ONCY",
            "ONEQ",
            "ONFC",
            "ONNN",
            "ONTX",
            "ONTY",
            "ONVI",
            "OPEN",
            "OPHC",
            "OPHT",
            "OPLK",
            "OPOF",
            "OPTT",
            "OPXA",
            "ORBC",
            "ORBK",
            "ORBT",
            "OREX",
            "ORIG",
            "ORIT",
            "ORLY",
            "ORMP",
            "ORRF",
            "OSBC",
            "OSBCP",
            "OSHC",
            "OSIR",
            "OSIS",
            "OSM",
            "OSN",
            "OSTK",
            "OSUR",
            "OTEL",
            "OTEX",
            "OTIV",
            "OTTR",
            "OUTR",
            "OVAS",
            "OVBC",
            "OVLY",
            "OVRL",
            "OVTI",
            "OXBT",
            "OXFD",
            "OXGN",
            "OXLC",
            "OXLCO",
            "OXLCP",
            "OZRK",
            "PAAS",
            "PACB",
            "PACR",
            "PACT          ",
            "PACW",
            "PAGG",
            "PAMT",
            "PATK",
            "PATR",
            "PAYX",
            "PBCP",
            "PBCT",
            "PBHC",
            "PBIB",
            "PBIP",
            "PBMD",
            "PBPB",
            "PBSK",
            "PCAR",
            "PCBK",
            "PCCC",
            "PCH",
            "PCLN",
            "PCMI",
            "PCO",
            "PCOM",
            "PCRX",
            "PCTI",
            "PCYC",
            "PCYG",
            "PCYO",
            "PDCE",
            "PDCO",
            "PDEX",
            "PDFS",
            "PDII",
            "PDLI",
            "PEBK",
            "PEBO",
            "PEGA",
            "PEGI",
            "PEIX",
            "PENN",
            "PENX",
            "PEOP",
            "PERF",
            "PERI",
            "PERY",
            "PESI",
            "PETM",
            "PETS",
            "PETX",
            "PFBC",
            "PFBI",
            "PFBX",
            "PFIN",
            "PFLT",
            "PFMT",
            "PFPT",
            "PFSW",
            "PGC",
            "PGNX",
            "PGRX",
            "PGTI",
            "PHII",
            "PHIIK",
            "PHMD",
            "PICO",
            "PINC",
            "PKBK",
            "PKOH",
            "PKT",
            "PLAB",
            "PLBC",
            "PLCC",
            "PLCE",
            "PLCM",
            "PLKI",
            "PLMT",
            "PLNR",
            "PLPC",
            "PLPM",
            "PLTM",
            "PLUG",
            "PLUS",
            "PLXS",
            "PLXT",
            "PMBC",
            "PMCS",
            "PMCT",
            "PMD",
            "PME",
            "PMFG",
            "PNBK",
            "PNFP",
            "PNNT",
            "PNQI",
            "PNRA",
            "PNRG",
            "PNTR",
            "PODD",
            "POOL",
            "POPE",
            "POWI",
            "POWL",
            "POZN",
            "PPBI",
            "PPC",
            "PPHM",
            "PPHMP",
            "PPSI",
            "PRAA",
            "PRAN",
            "PRCP",
            "PRFT",
            "PRFZ",
            "PRGN",
            "PRGS",
            "PRGX",
            "PRIM",
            "PRKR",
            "PRLS",
            "PRMW",
            "PROV",
            "PRPH",
            "PRSC",
            "PRSS",
            "PRTA",
            "PRTS",
            "PRXI",
            "PRXL",
            "PSAU",
            "PSBH",
            "PSCC",
            "PSCD",
            "PSCE",
            "PSCF",
            "PSCH",
            "PSCI",
            "PSCM",
            "PSCT",
            "PSCU",
            "PSDV",
            "PSEC",
            "PSEM",
            "PSIX",
            "PSMI",
            "PSMT",
            "PSTB",
            "PSTI",
            "PSTR",
            "PSUN",
            "PTC",
            "PTCT",
            "PTEK",
            "PTEN",
            "PTIE",
            "PTLA",
            "PTNR",
            "PTNT",
            "PTRY",
            "PTSI",
            "PTSX",
            "PTX",
            "PULB",
            "PVTB",
            "PVTBP",
            "PWOD",
            "PWRD",
            "PWX",
            "PXLW",
            "PZZA",
            "PZZI",
            "QABA",
            "QADA",
            "QADB",
            "QBAK",
            "QCCO",
            "QCLN",
            "QCOM",
            "QCOR",
            "QCRH",
            "QDEL",
            "QGEN",
            "QINC",
            "QIWI",
            "QKLS",
            "QLGC",
            "QLIK",
            "QLTI",
            "QLTY",
            "QLYS",
            "QNST",
            "QPAC",
            "QPACU",
            "QPACW",
            "QQEW",
            "QQQ",
            "QQQC",
            "QQQX",
            "QQXT",
            "QSII",
            "QTEC",
            "QTET",
            "QTETR",
            "QTETU",
            "QTWW",
            "QUIK",
            "QUMU",
            "QUNR",
            "QURE",
            "QYLD",
            "RADA",
            "RAIL",
            "RAND",
            "RARE",
            "RAVN",
            "RBCAA",
            "RBCN",
            "RBPAA",
            "RCII",
            "RCKB",
            "RCKY",
            "RCMT",
            "RCON",
            "RCPT",
            "RDA",
            "RDCM",
            "RDEN",
            "RDHL",
            "RDI",
            "RDIB",
            "RDNT",
            "RDVY",
            "RDWR",
            "RECN",
            "REDF",
            "REFR",
            "REGI",
            "REGN",
            "REIS",
            "RELL",
            "RELV",
            "REMY",
            "RENT",
            "REPH",
            "REXI",
            "REXX",
            "RFIL",
            "RFMD",
            "RGCO",
            "RGDO",
            "RGDX",
            "RGEN",
            "RGLD",
            "RGLS",
            "RGSE",
            "RIBT",
            "RIBTW",
            "RICK",
            "RIGL",
            "RITT",
            "RITTW",
            "RIVR",
            "RJET",
            "RLJE",
            "RLOC",
            "RLOG",
            "RLYP",
            "RMBS",
            "RMCF",
            "RMGN",
            "RMTI",
            "RNA",
            "RNET",
            "RNST",
            "RNWK",
            "ROBO",
            "ROCK",
            "ROIA",
            "ROIAK",
            "ROIC",
            "ROICU",
            "ROICW",
            "ROIQ",
            "ROIQU",
            "ROIQW",
            "ROLL",
            "ROSE",
            "ROSG",
            "ROST",
            "ROVI",
            "ROYL",
            "RP",
            "RPRX",
            "RPRXW",
            "RPRXZ",
            "RPTP",
            "RPXC",
            "RRD",
            "RRGB",
            "RRST",
            "RSTI",
            "RSYS",
            "RTIX",
            "RTK",
            "RTRX",
            "RUDR",
            "RUSHA",
            "RUSHB",
            "RUTH",
            "RVBD",
            "RVLT",
            "RVNC",
            "RVSB",
            "RXII",
            "RYAAY",
            "SAAS",
            "SAEX",
            "SAFM",
            "SAFT",
            "SAIA",
            "SAL",
            "SALE",
            "SALM",
            "SAMG",
            "SANM",
            "SANW",
            "SANWZ",
            "SAPE",
            "SASR",
            "SATS",
            "SAVE",
            "SBAC",
            "SBBX",
            "SBCF",
            "SBFG",
            "SBGI",
            "SBLK",
            "SBNY",
            "SBNYW",
            "SBRA",
            "SBRAP",
            "SBSA",
            "SBSI",
            "SBUX",
            "SCAI",
            "SCBT",
            "SCHL",
            "SCHN",
            "SCLN",
            "SCMP",
            "SCOK",
            "SCON",
            "SCOR",
            "SCSC",
            "SCSS",
            "SCTY",
            "SCVL",
            "SEAC",
            "SEED",
            "SEIC",
            "SENEA",
            "SENEB",
            "SEV",
            "SFBC",
            "SFLY",
            "SFM",
            "SFNC",
            "SFST",
            "SFXE",
            "SGC",
            "SGEN",
            "SGI",
            "SGMA",
            "SGMO",
            "SGMS",
            "SGNT",
            "SGOC",
            "SGRP",
            "SGYP",
            "SGYPU",
            "SGYPW",
            "SHBI",
            "SHEN",
            "SHIP",
            "SHLD",
            "SHLM",
            "SHLO",
            "SHOO",
            "SHOR",
            "SHOS",
            "SHPG",
            "SIAL",
            "SIBC",
            "SIEB",
            "SIFI",
            "SIFY",
            "SIGA",
            "SIGI",
            "SIGM",
            "SILC",
            "SIMG",
            "SIMO",
            "SINA",
            "SINO",
            "SIRI",
            "SIRO",
            "SIVB",
            "SIVBO",
            "SKBI",
            "SKUL",
            "SKYW",
            "SKYY",
            "SLAB",
            "SLGN",
            "SLM",
            "SLMAP",
            "SLMBP",
            "SLP",
            "SLRC",
            "SLTC",
            "SLVO",
            "SLXP",
            "SMBC",
            "SMCI",
            "SMED",
            "SMIT",
            "SMLR",
            "SMMF",
            "SMPL",
            "SMRT",
            "SMSI",
            "SMT",
            "SMTC",
            "SMTP",
            "SMTX",
            "SNAK",
            "SNBC",
            "SNCR",
            "SNDK",
            "SNFCA",
            "SNHY",
            "SNMX",
            "SNPS",
            "SNSS",
            "SNTA",
            "SOCB",
            "SOCL",
            "SODA",
            "SOFO",
            "SOHO",
            "SOHOL",
            "SOHU",
            "SONA",
            "SONC",
            "SONS",
            "SORL",
            "SOXX",
            "SP",
            "SPAN",
            "SPAR",
            "SPBC",
            "SPCB",
            "SPCHA",
            "SPCHB",
            "SPDC",
            "SPEX",
            "SPHS",
            "SPIL",
            "SPLK",
            "SPLS",
            "SPNC",
            "SPNS",
            "SPPI",
            "SPPR",
            "SPPRO",
            "SPPRP",
            "SPRO",
            "SPRT",
            "SPSC",
            "SPTN",
            "SPU",
            "SPWR",
            "SQBG",
            "SQI",
            "SQNM",
            "SQQQ",
            "SRCE",
            "SRCL",
            "SRDX",
            "SREV",
            "SRNE",
            "SRPT",
            "SSBI",
            "SSFN",
            "SSH",
            "SSNC",
            "SSRI",
            "SSYS",
            "STAA",
            "STB",
            "STBA",
            "STBZ",
            "STCK",
            "STEM",
            "STFC",
            "STKL",
            "STLD",
            "STLY",
            "STML",
            "STMP",
            "STNR",
            "STRA",
            "STRL",
            "STRM",
            "STRN",
            "STRS",
            "STRT",
            "STRZA",
            "STRZB",
            "STSA",
            "STSI",
            "STX",
            "STXS",
            "SUBK",
            "SUMR",
            "SUNS",
            "SUPN",
            "SUPX",
            "SURG",
            "SUSQ",
            "SUTR",
            "SVA",
            "SVBI",
            "SVVC",
            "SWHC",
            "SWIR",
            "SWKS",
            "SWSH",
            "SYBT",
            "SYKE",
            "SYMC",
            "SYMX",
            "SYNA",
            "SYNC",
            "SYNL",
            "SYNM",
            "SYNT",
            "SYPR",
            "SYUT",
            "SZMK",
            "SZYM",
            "TACT",
            "TAIT",
            "TASR",
            "TAST",
            "TATT",
            "TAX",
            "TAXI",
            "TAYC",
            "TAYCO",
            "TAYCP",
            "TAYD",
            "TBBK",
            "TBNK",
            "TBOW",
            "TCBI",
            "TCBIL",
            "TCBIP",
            "TCBIW",
            "TCBK",
            "TCCO",
            "TCFC",
            "TCPC",
            "TCRD",
            "TCX",
            "TDIV",
            "TEAR",
            "TECD",
            "TECH",
            "TECUA",
            "TECUB",
            "TELK",
            "TESO",
            "TESS",
            "TFM",
            "TFSL",
            "TGA",
            "TGE",
            "TGLS",
            "TGTX",
            "THFF",
            "THLD",
            "THOR",
            "THRD",
            "THRM",
            "THRX",
            "THST",
            "THTI",
            "TIBX",
            "TICC",
            "TIGR",
            "TILE",
            "TINY",
            "TIPT",
            "TISA",
            "TITN",
            "TIVO",
            "TKMR",
            "TLF",
            "TLMR",
            "TLOG",
            "TMNG",
            "TNAV",
            "TNDM",
            "TNGO",
            "TNXP",
            "TOFC",
            "TOPS",
            "TORM          ",
            "TOWN",
            "TQNT",
            "TQQQ",
            "TRAK",
            "TRCB",
            "TRCH",
            "TREE",
            "TRGT",
            "TRIB",
            "TRIP",
            "TRIT",
            "TRMB",
            "TRMK",
            "TRNS",
            "TRNX",
            "TROV",
            "TROVU",
            "TROVW",
            "TROW",
            "TRS",
            "TRST",
            "TRVN",
            "TSBK",
            "TSC",
            "TSCO",
            "TSEM",
            "TSLA",
            "TSPT",
            "TSRA",
            "TSRE",
            "TSRI",
            "TSRO",
            "TST",
            "TSYS",
            "TTEC",
            "TTEK",
            "TTGT",
            "TTHI",
            "TTMI",
            "TTPH",
            "TTS",
            "TTWO",
            "TUES",
            "TVIX",
            "TVIZ",
            "TWER",
            "TWGP",
            "TWIN",
            "TWMC",
            "TWTC",
            "TXN",
            "TXRH",
            "TYPE",
            "TZOO",
            "UACL",
            "UBCP",
            "UBFO",
            "UBIC",
            "UBNK",
            "UBNT",
            "UBOH",
            "UBSH",
            "UBSI",
            "UCBA",
            "UCBI",
            "UCFC",
            "UCTT",
            "UEIC",
            "UEPS",
            "UFCS",
            "UFPI",
            "UFPT",
            "UG",
            "UGLD",
            "UHAL",
            "UIHC",
            "ULBI",
            "ULTA",
            "ULTI",
            "ULTR",
            "UMBF",
            "UMPQ",
            "UNAM",
            "UNB",
            "UNFI",
            "UNIS",
            "UNTD",
            "UNTK",
            "UNTY",
            "UNXL",
            "UPI",
            "UPIP",
            "URBN",
            "URRE",
            "USAK",
            "USAP",
            "USAT",
            "USATP",
            "USBI",
            "USCR",
            "USEG",
            "USLM",
            "USLV",
            "USMD",
            "USMO",
            "USTR",
            "UTEK",
            "UTHR",
            "UTIW",
            "UTMD",
            "UTSI",
            "UVSP",
            "VALU",
            "VASC",
            "VBFC",
            "VCIT",
            "VCLT",
            "VCSH",
            "VCYT",
            "VDSI",
            "VECO",
            "VGIT",
            "VGLT",
            "VGSH",
            "VIA",
            "VIAB",
            "VIAS",
            "VICL",
            "VICR",
            "VIDE",
            "VIDI",
            "VIEW",
            "VIIX",
            "VIIZ",
            "VIMC",
            "VIP",
            "VIRC",
            "VISN",
            "VITC",
            "VIVO",
            "VLCCF",
            "VLGEA",
            "VLTC",
            "VLYWW",
            "VMBS",
            "VNDA",
            "VNET",
            "VNQI",
            "VNR",
            "VNRAP",
            "VNRBP",
            "VOCS",
            "VOD",
            "VOLC",
            "VONE",
            "VONG",
            "VONV",
            "VOXX",
            "VPFG",
            "VPRT",
            "VRA",
            "VRML",
            "VRNG",
            "VRNGW",
            "VRNS",
            "VRNT",
            "VRSK",
            "VRSN",
            "VRTA",
            "VRTB",
            "VRTS",
            "VRTU",
            "VRTX",
            "VSAT",
            "VSCI",
            "VSCP",
            "VSEC",
            "VSTM",
            "VTHR",
            "VTIP",
            "VTNC",
            "VTNR",
            "VTSS",
            "VTUS",
            "VTWG",
            "VTWO",
            "VTWV",
            "VUSE",
            "VVTV",
            "VVUS",
            "VWOB",
            "VXUS",
            "VYFC",
            "WABC",
            "WAFD",
            "WAFDW",
            "WASH",
            "WAVX",
            "WAYN",
            "WBB",
            "WBCO",
            "WBKC",
            "WBMD",
            "WDC",
            "WDFC",
            "WEBK",
            "WEN",
            "WERN",
            "WETF",
            "WEYS",
            "WFBI",
            "WFD",
            "WFM",
            "WHF",
            "WHFBL",
            "WHLR",
            "WIBC",
            "WIFI",
            "WILC",
            "WILN",
            "WIN",
            "WINA",
            "WIRE",
            "WIX",
            "WLB",
            "WLBPZ",
            "WLDN",
            "WLFC",
            "WMAR",
            "WMGI",
            "WMGIZ",
            "WOOD",
            "WOOF",
            "WPCS",
            "WPPGY",
            "WPRT",
            "WRES",
            "WRLD",
            "WSBC",
            "WSBF",
            "WSCI",
            "WSFS",
            "WSFSL",
            "WSTC",
            "WSTG",
            "WSTL",
            "WTBA",
            "WTFC",
            "WTFCW",
            "WTSL",
            "WVFC",
            "WVVI",
            "WWD",
            "WWWW",
            "WYNN",
            "XBKS",
            "XGTI",
            "XGTIW",
            "XIV",
            "XLNX",
            "XLRN",
            "XNCR",
            "XNPT",
            "XOMA",
            "XONE",
            "XOOM",
            "XPLR",
            "XRAY",
            "XRSC",
            "XRTX",
            "XTLB",
            "XWES",
            "XXIA",
            "YDIV",
            "YDKN",
            "YHOO",
            "YNDX",
            "YOD",
            "YONG",
            "YORW",
            "YPRO",
            "YRCW",
            "YY",
            "Z",
            "ZAGG",
            "ZAZA",
            "ZBRA",
            "ZEUS",
            "ZGNX",
            "ZHNE",
            "ZIGO",
            "ZINC",
            "ZION",
            "ZIONW",
            "ZIONZ",
            "ZIOP",
            "ZIPR",
            "ZIV",
            "ZIXI",
            "ZLCS",
            "ZLTQ",
            "ZN",
            "ZNGA",
            "ZOOM",
            "ZU",
            "ZUMZ"});
            this.txtSymbol.Location = new System.Drawing.Point(10, 12);
            this.txtSymbol.Name = "txtSymbol";
            this.txtSymbol.Size = new System.Drawing.Size(121, 21);
            this.txtSymbol.TabIndex = 54;
            this.txtSymbol.Text = "AAIT";
            this.txtSymbol.SelectedIndexChanged += new System.EventHandler(this.txtSymbol_SelectedIndexChanged);
            // 
            // button9
            // 
            this.button9.BackColor = System.Drawing.SystemColors.Control;
            this.button9.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.button9.Location = new System.Drawing.Point(579, 514);
            this.button9.Name = "button9";
            this.button9.Size = new System.Drawing.Size(75, 23);
            this.button9.TabIndex = 53;
            this.button9.Text = "max";
            this.button9.UseVisualStyleBackColor = false;
            this.button9.Click += new System.EventHandler(this.button9_Click);
            // 
            // button8
            // 
            this.button8.BackColor = System.Drawing.SystemColors.Control;
            this.button8.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.button8.Location = new System.Drawing.Point(497, 514);
            this.button8.Name = "button8";
            this.button8.Size = new System.Drawing.Size(75, 23);
            this.button8.TabIndex = 52;
            this.button8.Text = "5 years";
            this.button8.UseVisualStyleBackColor = false;
            this.button8.Click += new System.EventHandler(this.button8_Click);
            // 
            // button7
            // 
            this.button7.BackColor = System.Drawing.SystemColors.Control;
            this.button7.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.button7.Location = new System.Drawing.Point(416, 514);
            this.button7.Name = "button7";
            this.button7.Size = new System.Drawing.Size(75, 23);
            this.button7.TabIndex = 51;
            this.button7.Text = "2 years";
            this.button7.UseVisualStyleBackColor = false;
            this.button7.Click += new System.EventHandler(this.button7_Click);
            // 
            // button6
            // 
            this.button6.BackColor = System.Drawing.SystemColors.Control;
            this.button6.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.button6.Location = new System.Drawing.Point(335, 514);
            this.button6.Name = "button6";
            this.button6.Size = new System.Drawing.Size(75, 23);
            this.button6.TabIndex = 50;
            this.button6.Text = "1 year";
            this.button6.UseVisualStyleBackColor = false;
            this.button6.Click += new System.EventHandler(this.button6_Click);
            // 
            // button5
            // 
            this.button5.BackColor = System.Drawing.SystemColors.Control;
            this.button5.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.button5.Location = new System.Drawing.Point(254, 514);
            this.button5.Name = "button5";
            this.button5.Size = new System.Drawing.Size(75, 23);
            this.button5.TabIndex = 49;
            this.button5.Text = "6 months";
            this.button5.UseVisualStyleBackColor = false;
            this.button5.Click += new System.EventHandler(this.button5_Click);
            // 
            // button4
            // 
            this.button4.BackColor = System.Drawing.SystemColors.Control;
            this.button4.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.button4.Location = new System.Drawing.Point(173, 514);
            this.button4.Name = "button4";
            this.button4.Size = new System.Drawing.Size(75, 23);
            this.button4.TabIndex = 48;
            this.button4.Text = "3 months";
            this.button4.UseVisualStyleBackColor = false;
            this.button4.Click += new System.EventHandler(this.button4_Click);
            // 
            // button3
            // 
            this.button3.BackColor = System.Drawing.SystemColors.Control;
            this.button3.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.button3.Location = new System.Drawing.Point(91, 514);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(75, 23);
            this.button3.TabIndex = 47;
            this.button3.Text = "5 days";
            this.button3.UseVisualStyleBackColor = false;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.SystemColors.Control;
            this.button2.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.button2.Location = new System.Drawing.Point(10, 514);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(75, 23);
            this.button2.TabIndex = 46;
            this.button2.Text = "1 day";
            this.button2.UseVisualStyleBackColor = false;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.SystemColors.Control;
            this.pictureBox1.Location = new System.Drawing.Point(10, 207);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(640, 301);
            this.pictureBox1.TabIndex = 45;
            this.pictureBox1.TabStop = false;
            // 
            // Form7
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(665, 549);
            this.Controls.Add(this.labelEPSEstimateCurrentYear);
            this.Controls.Add(this.labelPERatio);
            this.Controls.Add(this.labelDividendShare);
            this.Controls.Add(this.labelMarketCap);
            this.Controls.Add(this.labelAsk);
            this.Controls.Add(this.labelBid);
            this.Controls.Add(this.labelAverageDailyVolume);
            this.Controls.Add(this.labelVolume);
            this.Controls.Add(this.labelweek52Range);
            this.Controls.Add(this.labelDaysRange);
            this.Controls.Add(this.labelOpen);
            this.Controls.Add(this.labelPreviousClose);
            this.Controls.Add(this.labelChangePercentChange);
            this.Controls.Add(this.labelPrice);
            this.Controls.Add(this.labelLastTradeTime);
            this.Controls.Add(this.labelSymbol);
            this.Controls.Add(this.label17);
            this.Controls.Add(this.label16);
            this.Controls.Add(this.label15);
            this.Controls.Add(this.label14);
            this.Controls.Add(this.label13);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.txtSymbol);
            this.Controls.Add(this.button9);
            this.Controls.Add(this.button8);
            this.Controls.Add(this.button7);
            this.Controls.Add(this.button6);
            this.Controls.Add(this.button5);
            this.Controls.Add(this.button4);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.pictureBox1);
            this.Name = "Form7";
            this.Text = "Form7";
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label labelEPSEstimateCurrentYear;
        private System.Windows.Forms.Label labelPERatio;
        private System.Windows.Forms.Label labelDividendShare;
        private System.Windows.Forms.Label labelMarketCap;
        private System.Windows.Forms.Label labelAsk;
        private System.Windows.Forms.Label labelBid;
        private System.Windows.Forms.Label labelAverageDailyVolume;
        private System.Windows.Forms.Label labelVolume;
        private System.Windows.Forms.Label labelweek52Range;
        private System.Windows.Forms.Label labelDaysRange;
        private System.Windows.Forms.Label labelOpen;
        private System.Windows.Forms.Label labelPreviousClose;
        private System.Windows.Forms.Label labelChangePercentChange;
        private System.Windows.Forms.Label labelPrice;
        private System.Windows.Forms.Label labelLastTradeTime;
        private System.Windows.Forms.Label labelSymbol;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.ComboBox txtSymbol;
        private System.Windows.Forms.Button button9;
        private System.Windows.Forms.Button button8;
        private System.Windows.Forms.Button button7;
        private System.Windows.Forms.Button button6;
        private System.Windows.Forms.Button button5;
        private System.Windows.Forms.Button button4;
        private System.Windows.Forms.Button button3;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.PictureBox pictureBox1;
    }
}